# Dataset Preprocessing

## Importing libraries

In [53]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import numpy as np
from IPython.display import display
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder

from neuralol.constants import Role, StatsCols, NewFeature
from neuralol.data import get_model_players_game_features

pd.set_option('display.max_columns', None)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## Load data

In [54]:
df_players_game_stats = pd.read_csv('../data/raw/game_players_stats.csv')
print(f"{df_players_game_stats.shape[0]} rows and {df_players_game_stats.shape[1]} columns")
display(df_players_game_stats.head(10))

df_players_game_stats.describe(percentiles=[.01, .05, .25, .5, .75, .95, .99])

374554 rows and 28 columns

,game_id,player_id,player_name,team_id,team_name,team_acronym,role,win,game_length,champion_name,team_kills,tower_kills,inhibitor_kills,dragon_kills,herald_kills,baron_kills,player_kills,player_deaths,player_assists,total_minions_killed,gold_earned,level,total_damage_dealt,total_damage_dealt_to_champions,total_damage_taken,wards_placed,largest_killing_spree,largest_multi_kill
0,15,0,shanji,0,Legend Esport Gaming,LEG,Top,False,1415,Irelia,7,3,0,0,0,0,2,5,1,179,8530,12,99007,7923,15326,8,0,1
1,15,1,Demon,1,Bilibili Gaming Junior,BLGJ,Top,True,1415,Vladimir,17,8,1,3,1,1,2,3,6,174,8565,14,100342,10857,16475,11,2,1
2,15,2,yanxuan,0,Legend Esport Gaming,LEG,Bot,False,1415,Kai'Sa,7,3,0,0,0,0,2,2,1,227,9613,12,116407,7011,5788,9,0,1
3,15,3,Viod,0,Legend Esport Gaming,LEG,Support,False,1415,Lux,7,3,0,0,0,0,0,4,2,19,5442,10,23555,4932,6151,25,0,0
4,15,4,HanXuan,1,Bilibili Gaming Junior,BLGJ,Mid,True,1415,Aatrox,17,8,1,3,1,1,4,2,4,188,10125,14,125022,10749,15481,10,3,2
5,15,5,Yui,1,Bilibili Gaming Junior,BLGJ,Support,True,1415,Alistar,17,8,1,3,1,1,1,1,11,45,7615,12,27332,2889,8318,25,0,1
6,15,6,Chieftain,1,Bilibili Gaming Junior,BLGJ,Jungle,True,1415,Gragas,17,8,1,3,1,1,5,0,5,129,9686,13,121081,7263,18191,19,5,1
7,15,7,Virus,1,Bilibili Gaming Junior,BLGJ,Bot,True,1415,Xayah,17,8,1,3,1,1,5,1,3,249,12122,14,147097,9059,8442,9,3,2
8,15,8,Assassin,0,Legend Esport Gaming,LEG,Mid,False,1415,Akali,7,3,0,0,0,0,3,5,0,193,9434,13,114025,11373,18390,6,2,1
9,15,9,CatJug,0,Legend Esport Gaming,LEG,Jungle,False,1415,Sejuani,7,3,0,0,0,0,0,1,4,167,8511,13,128180,5912,16508,6,0,0

,game_id,player_id,team_id,game_length,team_kills,tower_kills,inhibitor_kills,dragon_kills,herald_kills,baron_kills,player_kills,player_deaths,player_assists,total_minions_killed,gold_earned,level,total_damage_dealt,total_damage_dealt_to_champions,total_damage_taken,wards_placed,largest_killing_spree,largest_multi_kill
count,374554.000000,374554.000000,374554.000000,3.745540e+05,374554.000000,374554.000000,374554.000000,374554.000000,374554.000000,374554.000000,374554.000000,374554.000000,374554.000000,374554.000000,374554.000000,374554.000000,374554.000000,374554.000000,374554.000000,374554.000000,374554.000000,374554.000000
mean,18729.401448,1549.469631,283.521236,2.376872e+03,13.915163,6.018486,0.895227,2.262723,0.885904,0.696305,2.783038,2.788671,6.393858,204.271643,11472.205180,14.789699,155852.709826,13792.472418,19392.803756,20.362722,1.762427,1.060029
std,10813.836519,1234.016945,222.844447,3.202794e+04,7.267931,3.618850,1.065168,1.400929,0.759774,0.741653,2.683247,1.947362,4.446742,105.844330,3389.038142,2.184600,92223.609967,8750.449083,9394.270675,18.232569,2.250181,0.833039
min,0.000000,0.000000,0.000000,8.060000e+02,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1920.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1%,374.000000,33.000000,5.000000,1.299000e+03,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,12.000000,5316.000000,10.000000,11445.530000,2087.000000,4978.000000,0.000000,0.000000,0.000000
5%,1872.000000,120.000000,25.000000,1.435000e+03,3.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,28.000000,6472.000000,11.000000,15928.000000,3327.650000,7587.000000,6.000000,0.000000,0.000000
25%,9363.000000,480.000000,86.000000,1.682000e+03,8.000000,3.000000,0.000000,1.000000,0.000000,0.000000,1.000000,1.000000,3.000000,147.000000,8911.000000,13.000000,102675.750000,7145.000000,12421.000000,10.000000,0.000000,1.000000
50%,18731.000000,1221.000000,221.000000,1.873000e+03,14.000000,7.000000,1.000000,2.000000,1.000000,1.000000,2.000000,3.000000,6.000000,220.000000,11243.000000,15.000000,158449.000000,12180.000000,17574.000000,14.000000,0.000000,1.000000
75%,28094.000000,2409.000000,449.000000,2.111000e+03,19.000000,9.000000,1.000000,3.000000,1.000000,1.000000,4.000000,4.000000,9.000000,277.000000,13635.000000,16.000000,209655.500000,18340.000000,24689.000000,21.000000,3.000000,1.000000
95%,35586.000000,3965.000000,699.000000,2.531000e+03,26.000000,11.000000,3.000000,4.000000,2.000000,2.000000,8.000000,6.000000,15.000000,360.000000,17422.000000,18.000000,309147.100000,30181.350000,36953.000000,61.000000,6.000000,3.000000
99%,37084.000000,4599.000000,796.000000,2.879000e+03,31.000000,11.000000,4.000000,5.000000,2.000000,3.000000,11.000000,8.000000,19.000000,427.000000,20583.470000,18.000000,407536.760000,41913.470000,48148.470000,86.000000,9.000000,3.000000
max,37458.000000,4952.000000,843.000000,2.793607e+06,79.000000,11.000000,10.000000,7.000000,3.000000,5.000000,28.000000,20.000000,35.000000,673.000000,31844.000000,18.000000,880083.000000,102344.000000,124663.000000,203.000000,22.000000,5.000000

In [55]:
print(f"Number of different games: {df_players_game_stats[StatsCols.GAME_ID].nunique()}")
print(f"Number of different players: {df_players_game_stats[StatsCols.PLAYER_ID].nunique()}")
print(f"Number of different teams: {df_players_game_stats[StatsCols.TEAM_ID].nunique()}")
# Check missing values in players_game_stats
print("\nMissing values in players_game_stats:")
missing_values = df_players_game_stats.isna().sum()
print(missing_values[missing_values > 0])  # Only show columns with missing values

# Percentage of missing values
print("\nPercentage of missing values:")
percent_missing = (missing_values / df_players_game_stats.shape[0]) * 100
print(percent_missing[percent_missing > 0])  # Only show columns with missing values

Number of different games: 37459
Number of different players: 4953
Number of different teams: 844

Missing values in players_game_stats:
team_acronym    290
dtype: int64

Percentage of missing values:
team_acronym    0.077425
dtype: float64

## Missing values & outliers

In [56]:
# Drop team_acronym column as it has missing values and do not provide any useful information
processed_players_game_stats = df_players_game_stats.drop(columns=[StatsCols.TEAM_ACRONYM])

In [57]:
# Remove outliers: game_length > 3600 (1 hour) and wards_placed > 120
processed_players_game_stats = processed_players_game_stats[
    (processed_players_game_stats[StatsCols.GAME_LENGTH] <= 3600) &
    (processed_players_game_stats[StatsCols.WARDS_PLACED] <= 120)
]
processed_players_game_stats[[StatsCols.GAME_LENGTH, StatsCols.WARDS_PLACED]].describe(percentiles=[.01, .05, .25, .5, .75, .95, .99])

         game_length   wards_placed
count  374079.000000  374079.000000
mean     1914.158151      20.259432
std       334.942078      17.916448
min       806.000000       0.000000
1%       1299.000000       0.000000
5%       1435.000000       6.000000
25%      1681.000000      10.000000
50%      1872.000000      13.000000
75%      2110.000000      21.000000
95%      2527.000000      60.000000
99%      2868.000000      84.000000
max      3533.000000     120.000000

## One-hot encoding

Since `object`/`str` type columns are more of a metadata information (player name, champ name...) rather than actual useful info to determine the player's game win, no encoding is needed.

## Feature creation & selection

In [58]:
df_processed = processed_players_game_stats.copy()
# KLA ratio
df_processed[NewFeature.KLA] = (df_processed[StatsCols.PLAYER_KILLS] + df_processed[StatsCols.PLAYER_ASSISTS]) / (df_processed[StatsCols.PLAYER_DEATHS] + 1)
# Objective Control Score: weighted sum of dragon_kills, herald_kills, baron_kills
df_processed[NewFeature.OBJECTIVES_CONTROL] = (df_processed[StatsCols.DRAGON_KILLS] * 10 +
                                      df_processed[StatsCols.HERALD_KILLS] * 10 +
                                      df_processed[StatsCols.BARON_KILLS] * 50)
# Tower control score: weighted sum of tower_kills and inhibitor_kills
df_processed[NewFeature.TOWER_CONTROL] = (df_processed[StatsCols.TOWER_KILLS] * 5 + df_processed[StatsCols.INHIBITOR_KILLS] * 20)
# Gold per minute
df_processed[NewFeature.GOLD_PER_MIN] = df_processed[StatsCols.GOLD_EARNED] / (df_processed[StatsCols.GAME_LENGTH] / 60)
# Level per minute
df_processed[NewFeature.LEVEL_PER_MIN] = df_processed[StatsCols.LEVEL] / (df_processed[StatsCols.GAME_LENGTH] / 60)
# CS per minute
df_processed[NewFeature.CS_PER_MIN] = df_processed[StatsCols.TOTAL_MINIONS_KILLED] / (df_processed[StatsCols.GAME_LENGTH] / 60)
# Team kills per minute
df_processed[NewFeature.TEAM_KILLS_PER_MIN] = df_processed[StatsCols.TEAM_KILLS] / (df_processed[StatsCols.GAME_LENGTH] / 60)
# Total damage per minute
df_processed[NewFeature.TOTAL_DAMAGE_PER_MIN] = df_processed[StatsCols.TOTAL_DAMAGE_DEALT] / (df_processed[StatsCols.GAME_LENGTH] / 60)
# Damage to champions per minute
df_processed[NewFeature.DAMAGE_TO_CHAMPIONS_PER_MIN] = df_processed[StatsCols.TOTAL_DAMAGE_DEALT_TO_CHAMPIONS] / (df_processed[StatsCols.GAME_LENGTH] / 60)
# Damage taken per minute
df_processed[NewFeature.DAMAGE_TAKEN_PER_MIN] = df_processed[StatsCols.TOTAL_DAMAGE_TAKEN] / (df_processed[StatsCols.GAME_LENGTH] / 60)

model_input_features = get_model_players_game_features()
df_processed = df_processed[[
    StatsCols.GAME_ID,
    StatsCols.PLAYER_ID,
    StatsCols.PLAYER_NAME,
    StatsCols.TEAM_ID,
    StatsCols.TEAM_NAME,
    StatsCols.ROLE,
    StatsCols.WIN,
    StatsCols.CHAMPION_NAME] + model_input_features]
print(f"Processed columns: {df_processed.columns.tolist()}")

Processed columns: ['game_id', 'player_id', 'player_name', 'team_id', 'team_name', 'role', 'win', 'champion_name', 'kla', 'objectives_control', 'tower_control', 'gold_per_min', 'level_per_min', 'team_kills_per_min', 'largest_killing_spree', 'largest_multi_kill', 'cs_per_min', 'total_damage_per_min', 'damage_to_champions_per_min', 'damage_taken_per_min']

## Numerical features standardization

In [59]:
df_standardized = df_processed.copy()
df_standardized[model_input_features] = (df_processed[model_input_features] - df_processed[model_input_features].mean()) / df_processed[model_input_features].std()

df_standardized.describe()

,game_id,player_id,team_id,kla,objectives_control,tower_control,gold_per_min,level_per_min,team_kills_per_min,largest_killing_spree,largest_multi_kill,cs_per_min,total_damage_per_min,damage_to_champions_per_min,damage_taken_per_min
count,374079.000000,374079.000000,374079.000000,3.740790e+05,3.740790e+05,3.740790e+05,3.740790e+05,3.740790e+05,3.740790e+05,3.740790e+05,3.740790e+05,3.740790e+05,3.740790e+05,3.740790e+05,3.740790e+05
mean,18726.951107,1549.506190,283.498266,-1.155243e-16,-8.783037e-17,-2.644028e-17,-1.394953e-16,1.445098e-15,1.115354e-16,1.473970e-17,-5.667946e-17,6.686049e-18,-2.103066e-16,3.282242e-17,4.376323e-17
std,10812.926044,1234.081213,222.854506,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
min,0.000000,0.000000,0.000000,-9.791201e-01,-1.388977e+00,-1.273804e+00,-2.820607e+00,-6.326694e+00,-1.818931e+00,-7.835322e-01,-1.272785e+00,-2.077520e+00,-1.934243e+00,-1.762393e+00,-2.339467e+00
25%,9360.000000,480.000000,86.000000,-7.135088e-01,-9.696955e-01,-8.755363e-01,-7.208121e-01,-7.090833e-01,-7.755431e-01,-7.835322e-01,-7.243874e-02,-4.944906e-01,-4.364736e-01,-7.983969e-01,-7.706150e-01
50%,18728.000000,1221.000000,221.000000,-3.416529e-01,7.850847e-02,1.865119e-01,2.627638e-02,9.767343e-03,-1.119088e-01,-7.835322e-01,-7.243874e-02,2.910976e-01,1.507312e-01,-1.316099e-01,-1.821147e-01
75%,28087.500000,2407.000000,449.000000,3.489365e-01,7.074309e-01,7.175360e-01,7.054868e-01,6.919078e-01,6.337479e-01,5.494325e-01,-7.243874e-02,7.559600e-01,6.497438e-01,6.112394e-01,6.787213e-01
max,37458.000000,4952.000000,843.000000,8.582887e+00,5.529169e+00,5.496753e+00,6.805512e+00,6.575711e+00,9.493347e+00,8.991542e+00,4.728945e+00,3.135712e+00,5.692350e+00,7.389783e+00,7.940019e+00

## Save preprocessed data

In [60]:
import os

# Create directory if it doesn't exist
preprocessed_dir = '../data/preprocessed'
os.makedirs(preprocessed_dir, exist_ok=True)

# Save the processed dataframe to CSV
processed_filename = 'processed_game_players_stats.csv'
processed_file_path = os.path.join(preprocessed_dir, processed_filename)
df_processed.to_csv(processed_file_path, index=False)
print(f"Processed dataset saved to {processed_file_path}")

# Save the standardized dataframe to CSV
standardized_filename = 'standardized_game_players_stats.csv'
standardized_file_path = os.path.join(preprocessed_dir, standardized_filename)
df_standardized.to_csv(standardized_file_path, index=False)
print(f"Standardized dataset saved to {standardized_file_path}")

Processed dataset saved to ../data/preprocessed\processed_game_players_stats.csv
Standardized dataset saved to ../data/preprocessed\standardized_game_players_stats.csv