# LoL dataset visualization

### Importing libraries

In [10]:
import pandas as pd
from IPython.display import display

from importlib import reload
import neuralol
_ = reload(neuralol)

### Players game stats

In [6]:
players_game_stats = pd.read_csv('../data/raw/game_players_stats.csv')
print(f"{players_game_stats.shape[0]} rows and {players_game_stats.shape[1]} columns")
display(players_game_stats.head(10))

374554 rows and 28 columns

,game_id,player_id,player_name,team_id,team_name,team_acronym,role,win,game_length,champion_name,...,player_assists,total_minions_killed,gold_earned,level,total_damage_dealt,total_damage_dealt_to_champions,total_damage_taken,wards_placed,largest_killing_spree,largest_multi_kill
0,15,0,shanji,0,Legend Esport Gaming,LEG,Top,False,1415,Irelia,...,1,179,8530,12,99007,7923,15326,8,0,1
1,15,1,Demon,1,Bilibili Gaming Junior,BLGJ,Top,True,1415,Vladimir,...,6,174,8565,14,100342,10857,16475,11,2,1
2,15,2,yanxuan,0,Legend Esport Gaming,LEG,Bot,False,1415,Kai'Sa,...,1,227,9613,12,116407,7011,5788,9,0,1
3,15,3,Viod,0,Legend Esport Gaming,LEG,Support,False,1415,Lux,...,2,19,5442,10,23555,4932,6151,25,0,0
4,15,4,HanXuan,1,Bilibili Gaming Junior,BLGJ,Mid,True,1415,Aatrox,...,4,188,10125,14,125022,10749,15481,10,3,2
5,15,5,Yui,1,Bilibili Gaming Junior,BLGJ,Support,True,1415,Alistar,...,11,45,7615,12,27332,2889,8318,25,0,1
6,15,6,Chieftain,1,Bilibili Gaming Junior,BLGJ,Jungle,True,1415,Gragas,...,5,129,9686,13,121081,7263,18191,19,5,1
7,15,7,Virus,1,Bilibili Gaming Junior,BLGJ,Bot,True,1415,Xayah,...,3,249,12122,14,147097,9059,8442,9,3,2
8,15,8,Assassin,0,Legend Esport Gaming,LEG,Mid,False,1415,Akali,...,0,193,9434,13,114025,11373,18390,6,2,1
9,15,9,CatJug,0,Legend Esport Gaming,LEG,Jungle,False,1415,Sejuani,...,4,167,8511,13,128180,5912,16508,6,0,0

### Game metadata

In [7]:
players_game_stats = pd.read_csv('../data/raw/game_metadata.csv')
print(f"{players_game_stats.shape[0]} rows and {players_game_stats.shape[1]} columns")
display(players_game_stats.head(10))

37459 rows and 9 columns

,game_id,date,match_id,tournament_id,tournament_name,series_id,series_name,league_id,league_name
0,0,2019-09-15 10:17:30.487000,0,0,Playoffs,0,VCS Summer 2019,0,VCS
1,1,2019-09-15 11:18:01.085000,0,0,Playoffs,0,VCS Summer 2019,0,VCS
2,2,2019-09-15 12:11:33.489000,0,0,Playoffs,0,VCS Summer 2019,0,VCS
3,3,2019-09-15 13:03:19.662000,0,0,Playoffs,0,VCS Summer 2019,0,VCS
4,4,2019-09-16 04:32:28.724000,1,1,Playoffs,1,LJL Summer 2019,1,LJL
5,5,2019-09-16 05:29:41.680000,1,1,Playoffs,1,LJL Summer 2019,1,LJL
6,6,2019-09-16 06:45:07.195000,1,1,Playoffs,1,LJL Summer 2019,1,LJL
7,7,2019-09-16 07:45:59.496000,1,1,Playoffs,1,LJL Summer 2019,1,LJL
8,8,2019-09-15 15:08:08.817000,2,2,Regional Finals,2,LEC Summer 2019,2,LEC
9,9,2019-09-15 16:03:21.799000,2,2,Regional Finals,2,LEC Summer 2019,2,LEC

### Game events

In [8]:
players_game_stats = pd.read_csv('../data/raw/game_events.csv')
print(f"{players_game_stats.shape[0]} rows and {players_game_stats.shape[1]} columns")
display(players_game_stats.head(10))

1884740 rows and 8 columns

,id,game_id,timestamp,event_type,killer_id,killed_id,assisting_player_ids,drake_type
0,0,0,229,player_kill,21.0,29.0,[23],NaN
1,1,0,289,player_kill,21.0,29.0,[23],NaN
2,2,0,499,player_kill,25.0,21.0,"[29, 22]",NaN
3,3,0,504,player_kill,22.0,23.0,"[29, 25]",NaN
4,4,0,535,player_kill,28.0,24.0,[27],NaN
5,5,0,698,player_kill,28.0,24.0,"[21, 23, 30, 27]",NaN
6,6,0,700,player_kill,23.0,26.0,"[30, 28, 27]",NaN
7,7,0,705,player_kill,27.0,25.0,"[21, 30]",NaN
8,8,0,819,player_kill,28.0,24.0,[27],NaN
9,9,0,823,player_kill,22.0,28.0,[24],NaN